package main

const newTemplate = `package {{.Package}}
`

const queueTemplate = `
// {{.GolangTableName}} generated by DBGen struct
type {{.GolangTableName}} struct {
{{ range .DBStructures }}	{{ .GolangColumn }}	{{ .GolangDataType }}	` + "`" + `json:"{{ .Column }}" db:"{{ .Column }}"` + "`" + `
{{ end }}}`

const postgresToGolang = `
{
    "smallint" : "int",
    "integer" : "int32",
    "bigint" : "int64",
    "real" : "float32",
    "double precision" : "float64",
    "boolean" : "bool",
    "bytea" : "[]byte",
    "jsonb" : "map[string]interface{}",	
    "timestamp with time zone" : "time.Time",
    "date" : "time.Time",
    "timestamp without time zone" : "time.Time",
    "text" : "string",
    "character varying" : "string"
}`
